# Generated by Django 5.2.1 on 2025-06-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrequest',
            name='company_request_id',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='company_order_id',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
