# Generated by Django 5.2.1 on 2025-06-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='contact_Number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
