# Generated by Django 5.2.1 on 2025-06-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_company_logo_alter_staff_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='role',
        ),
    ]
