# Generated by Django 5.2.1 on 2025-06-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_staff_contact_number_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
