# Generated by Django 5.2.1 on 2025-07-10 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_audittrail_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_trails', to='dashboard.company'),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
