# Generated by Django 5.2.1 on 2025-06-11 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrequest',
            name='company_request_id',
            field=models.PositiveIntegerField( editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='company_order_id',
            field=models.PositiveIntegerField( editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryrequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_requests', to='dashboard.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='dashboard.OrderProduct', to='dashboard.product'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='dashboard.product'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryrequest',
            unique_together={('company', 'company_request_id')},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('company', 'company_order_id')},
        ),
    ]
