# Generated by Django 5.2.1 on 2025-06-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_order_date_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Stationary', 'Stationary'), ('Food', 'Food'), ('Toy', 'Toy'), ('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Furniture', 'Furniture'), ('Books', 'Books'), ('Sports', 'Sports'), ('Beauty', 'Beauty & Personal Care'), ('Health', 'Health & Wellness'), ('Automotive', 'Automotive'), ('Jewelry', 'Jewelry')], max_length=100, null=True),
        ),
    ]
