# Generated by Django 5.2.1 on 2025-06-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='must_update_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default='defaultpass123', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='visible_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
