# Generated by Django 5.2.1 on 2025-06-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_staff_join_date_alter_staff_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='join_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
