# Generated by Django 5.2.1 on 2025-06-06 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_order_product_alter_orderproduct_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_requests', to='dashboard.order'),
        ),
    ]
