# Generated by Django 5.2.1 on 2025-06-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_order_reviewed_by_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrail',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
