# Generated by Django 5.2.1 on 2025-07-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_audittrail_company_alter_audittrail_object_id'),
        ('dashboard', '0008_alter_staff_user'),
        ('dashboard', '0018_audittrail_object_id'),
    ]

    operations = [
    ]
